version: "3.7"

services:
  pipe-server:
    build:
      context: .
      args:
        NODE_ENV: local_docker
        
    depends_on:
      - mongo
    ports:
      - "8000:8080"
  mongo:
    image: mongo
    ports:
      - "27017:27017"