version: 2.1

machine:
  services:
    - docker

dependencies:
  cache_directories:
    - ~/docker

orbs:
  aws-cli: circleci/aws-cli@1.3.2
  heroku: circleci/heroku@1.2.4

jobs:
  testing-backend:
    docker:
      - image: circleci/node:10-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
          - server-{{ checksum "server/package.json" }}
          - server-
      - run:
          name: Installing dependencies
          command: |
            cd server
            npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "server/package.json" }}
      - run:
          name: Run tests
          command: |
            cd server
            npm run test

  deploy-backend:
    docker:
      - image: circleci/node:10-stretch
    steps:
      - checkout
      - heroku/install
      - run:
          name: "Install dependencies"
          command: |
            cd server
            npm install --production
      - run:
          name: "Build project"
          command: |
            cd server
            npm run build
      - run:
          name: "Build and tag docker image"
          command: |
            docker build -t registry.heroku.com/adapt-collate/web --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg NODE_ENV=production
      - heroku/push-docker-image
      - heroku/release-docker-image

  testing-frontend:
    docker:
      - image: circleci/node:10-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
          - app-{{ checksum "client/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - app-
      - run: 
          name: Installing dependencies
          command: |
            cd client
            npm install
      - save_cache: # Save node_modules into cache with a checksum of the package.json
          paths:
            - node_modules
          key: app-{{ checksum "client/package.json" }}
      - run: 
          name: Run tests
          command: |
            cd client
            npm run test # Run your tests

  deploy-frontend:
    docker:
      - image: circleci/node:10-stretch
    steps:
      - checkout
      - run:
          name: Preparing Artifact
          command: |
            cd client
            npm install
            npm run build # Here goes your build command.
            cd build       # My angular app generate a Dist folder
            zip ../build.zip -r * .[^.]* # Just zip your files
            echo "Sucessfully building"
      - aws-cli/setup:
          profile-name: circleci
          configure-default-region: false
      - run:
          name: Deploying Client to S3 and Cloudfront
          command: |
            aws configure set preview.cloudfront true  # Turn on cloudfront in AWS CLI
            if [ "${CIRCLE_BRANCH}" == "master" ]  # Check current branch to decide to which S3 bucket deploy
            then
              aws s3 sync ./client/build s3://pipe-production --delete
              aws cloudfront create-invalidation --distribution-id $PRODUCTION_DISTRIBUTION_ID --paths /\*
            elif [ "${CIRCLE_BRANCH}" == "staging" ]
            then
              # aws s3 sync ./client/build s3://staging.yoursite.com --delete
              # aws cloudfront create-invalidation --distribution-id DISTRIBUTION_ID_YOUR_SITE_STAGING --paths /\*
              echo "Have not created staging environment"
            elif [ "${CIRCLE_BRANCH}" == "dev" ]
            then
              # aws s3 sync ./client/build s3://dev.yoursite.com --delete
              # aws cloudfront create-invalidation --distribution-id DISTRIBUTION_ID_YOUR_SITE_DEV --paths /\*
              echo "Have not created dev environment"
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - testing-backend
      - deploy-backend:
          requires:
            - testing-backend   # Deploy require testing to be successful
          filters:
            branches:
              only:     # Only deploy for production, staging, and master branches
                - dev
                - staging
                - master
      - testing-frontend
      - deploy-frontend:
          requires:
            - testing-frontend   # Deploy require testing to be successful
          filters:
            branches:
              only:     # Only deploy for production, staging, and master branches
                - dev
                - staging
                - master