enum PostType {
    TWITCH_VIDEO = "TWITCH_VIDEO",
    TWITCH_STREAM = "TWITCH_STREAM",
    YOUTUBE_VIDEO = "YOUTUBE_VIDEO",
    TWEET = "TWEET",
    INSTAGRAM_POST = "INSTAGRAM_POST"
}

export default PostType;
