export default {
    InstagramPostRepository: Symbol.for("InstagramPostRepository"),
    TweetRepository: Symbol.for("TweetRepository"),
    TwitchStreamRepository: Symbol.for("TwitchStreamRepository"),
    TwitchVideoRepository: Symbol.for("TwitchVideoRepository"),
    UserRepository: Symbol.for("UserRepository"),
    WebhookRepository: Symbol.for("WebhookRepository"),
    YouTubeVideoRepository: Symbol.for("YouTubeVideoRepository"),
    PostRepository: Symbol.for("PostRepository"),
    RequiresAuthentication: Symbol.for("RequiresAuthentication"),
    Config: Symbol.for("Config"),
    PasswordManager: Symbol.for("PasswordManager"),
    TokenFactory: Symbol.for("TokenFactory"),
    TwitchAPIClient: Symbol.for("TwitchAPIClient"),
    YouTubeAPIClient: Symbol.for("YouTubeAPIClient"),
    InstagramAPIClient: Symbol.for("InstagramAPIClient"),
    TwitterAPIClient: Symbol.for("TwitterAPIClient"),
    UserService: Symbol.for("UserService"),
    SearchService: Symbol.for("SearchService"),
    TwitchWebhookCallbackService: Symbol.for("TwitchWebhookCallbackService"),
    YouTubeWebhookCallbackService: Symbol.for("YouTubeWebhookCallbackService"),
    FeedService: Symbol.for("FeedService"),
    AuthenticationService: Symbol.for("AuthenticationService"),
    InstagramChannelService: Symbol.for("InstagramChannelService"),
    TwitterChannelService: Symbol.for("TwitterChannelService"),
    TwitchChannelService: Symbol.for("TwitchChannelService"),
    YouTubeChannelService: Symbol.for("YouTubeChannelService")
};
